version: '3.1'

services:

  postgres_pagamentos:
    image: docker.io/postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432

  pgadmin:
    image: docker.io/dpage/pgadmin4:2023-04-11-2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "8081:80"