server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pagamentos
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  application:
    name: pagamentos-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s